config/routes.rb
Rails.application.routes.draw do

  resources :items do
  	resources :comments
  end

  resources :comments do 
  	resources :comments
  end

  root to: 'items#index'
  devise_for :users

  get '/items', to: 'items#index'
  # resources :item

  get 'items/new', to: 'items#new'
  post 'items', to: "items#create"

  get 'items/:id/edit', to: 'items#edit'
  get 'items/:id', to: 'items#show'
  patch 'items/:id', to: 'items#update'

  get 'users/:id', to: 'users#show', as: 'user'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  validates :username, presence: true
  validates :text, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
    belongs_to :user
    has_many :comments, as: :commentable
    has_many :comments, dependent: :destroy
    has_attached_file :avatar, styles: { medium: "300x300>" }
    validates_attachment_content_type :avatar, content_type: ["image/jpeg", "image/gif", "image/png"]
    validates :name, presence: true
    validates :price, presence: true

    def self.search(search)
        where("lower(name) LIKE ?", "%#{search.downcase}%")
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :items, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true

  def username
    self.email[/[^@]+/]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_commentable

	def new
		@comment = Comment.new
	end

	def create
		@comment = Comment.new comment_params
		@comment.save
		render :json => Comment.where(["item_id = ?", comment_params[:item_id].to_i])
	end

	private

	def comment_params
		params.require(:comment).permit(:username, :text, :item_id)
	end

	def find_commentable
		@commentable = Comment.find_by_id(params[:id]) if params[:id]
		@commentable = Item.find_by_id(params[:id]) if params[:id]
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        @items = Item.order(:id).where available: true
        if params[:search]
            @items = @items.search(params[:search])
        end
    end

	  def new
		    @item = Item.new #Creates an empty user object.
	  end

    def show
      @item = Item.find(params[:id])
      @presenter = {
        :comments => Comment.where("item_id = :id", { id: params[:id] }),
        :form => {
          :action => comments_path,
          :id => params[:id],
          :csrf_param => request_forgery_protection_token,
          :csrf_token => form_authenticity_token
        }
      }
    end

    def destroy
      @item = Item.find(params[:id])
      @item.destroy
      flash.notice = "Item removed successfully."
      redirect_to user_path(current_user.id)
    end

  	def create
    	  @item = Item.create(item_params)
    	  @item.available = true;
    	  @item.user_id = current_user.id
    	  if @item.save
    		    flash[:error] = nil
      		  redirect_to current_user
    	  else
    		    flash[:error] = @item.errors.full_messages.to_sentence
      		  render "new" #Go to the new view for
    	  end
  	end

    def edit
        @item = Item.find(params[:id])
    end

    def update
      @item = Item.find(params[:id])
      if params[:item][:name]
        @item.name = params[:item][:name]
      end
      if params[:item][:price]
        @item.price = params[:item][:price]
      end
      if params[:item][:description]
        @item.description = params[:item][:description]
      end

      @item.available = params[:item][:available]

      if @item.save
          redirect_to user_path(current_user.id)
      else
          render :action => :edit
      end
    end

    private
  	def item_params
  		  params.require(:item).permit(:name, :price, :description, :avatar)
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
      @user = User.find_by(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_item.html.erb
<div class="col-sm-6 col-md-4">
  <div class="item">
    <% if @user and @user == current_user %>
      <%= link_to "Edit item", edit_item_path(item.id), class: "btn btn-warning edit_button" %>
      <%= link_to "Remove item", item_path(item.id), method: :delete, class: "btn btn-danger remove_button" %>
    <% end %>
    <div style="font-weight:bold">
      <%= link_to item.name, item %>
    </div>
      User: <%= link_to User.find(item.user_id).username, user_path(item.user_id) %> <br>
      Price: <%= ActionController::Base.helpers.number_to_currency(item.price) %> <br>
      <% if item.avatar.file? %>
        <%= image_tag item.avatar.url(:medium), class: "img-thumbnail" %>
      <% else %>
        <%= image_tag image_url("missing.png"), class: "img-thumbnail" %>
      <% end %>
  </div>
</div>

app/views/items/edit.html.erb
<% content_for :devise_content do%>
  <h2>Edit Item</h2>

  <%= form_for(@item, html: { method: :patch, class: 'form-horizontal' }) do |f| %>
    <div class="form-group">
        <%= f.label :name, class: 'col-sm-2 control-label'  %>
        <div class="col-sm-6">
            <%= f.text_field :name, autofocus: true, required: true, class: 'form-control'  %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-6 col-sm-offset-2">
            <%= f.check_box :available %> <%= f.label :available %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label "Price ($)", class: 'col-sm-2 control-label'  %>
        <div class="col-sm-6">
            <%= f.number_field :price, class: 'form-control', required: true, :step => 0.01 %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :description, class: 'col-sm-2 control-label'  %>
        <div class="col-sm-6">
            <%= f.text_area :description, class: 'form-control'  %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
            <%= f.submit "Update", class: "btn btn-success" %>
        </div>
    </div>
  <% end %>

<% end %>

app/views/items/index.html.erb
<div class="page">

  <h2> Welcome to UCUtrade! </h2>
  <br>

  <div class="search">
    <h4> Search for items: </h4>
    <%= form_tag items_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Go", :name => nil %>
    <% end %>
  </div>

  <% if @items.empty? %>
    <br/>
    <p>Sorry, no results were found.</p>
  <% else %>
    <%= render @items %>
  <% end %>

</div>

app/views/items/new.html.erb
<% content_for :devise_content do%>
  <h2>New Item</h2>

  <%= form_for(@item, html: { method: :post, class: 'form-horizontal', multipart: true }) do |f| %>
    <div class="form-group">
        <%= f.label :name, class: 'col-sm-2 control-label'  %>
        <div class="col-sm-6">
            <%= f.text_field :name, autofocus: true, class: 'form-control', required: true %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label "Price ($)", class: 'col-sm-2 control-label'  %>
        <div class="col-sm-6">
            <%= f.number_field :price, class: 'form-control', required: true, :step => 0.01  %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :description, class: 'col-sm-2 control-label'  %>
        <div class="col-sm-6">
            <%= f.text_area :description, class: 'form-control'  %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :image, class: 'col-sm-2 control-label'  %>
        <div class="col-sm-6">
            <%= f.file_field :avatar, class: 'form-control'  %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
            <%= f.submit "Create", class: "btn btn-success" %>
        </div>
    </div>
  <% end %>

<% end %>

app/views/items/show.html.erb
<div class="page">
  <h1>Item Page</h1>
  <br/>
  <h2><%=@item.name%></h2>
  <p>User: <%= link_to User.find(@item.user_id).username, user_path(@item.user_id)%></p>
  <p>Price: <%= ActionController::Base.helpers.number_to_currency(@item.price) %></p>
  <p><strong>Description: </strong><%=@item.description%></p>
  <div style="width: 300px; height: 300px;">
    <% if @item.avatar.file? %>
      <%= image_tag @item.avatar.url(:medium), class: "img-thumbnail"%>
    <% else %>
      <%= image_tag image_url("missing.png"), class: "img-thumbnail"%>
    <% end %>
  </div>
  <br>
  <%= react_component('CommentBox', {:presenter => @presenter.to_json}, {:prerender => true}) %>
</div>

app/views/items/showItem.html.erb
<ul>
	<% @comments.each do |comment| %>
		<li><%= comment.text %></li>
	<% end %>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">UCUtrade</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <%= render "layouts/navbar_links" %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_links.html.erb
<% if current_user %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%='Hi, '+current_user.username%> <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Manage Items', user_path(current_user.id) %></li>
      <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
    </ul>
  </li>
  <li><%= link_to 'Log out', destroy_user_session_path, method: 'delete' %></li>
<% else %>
  <li><%= link_to 'Log in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UCUtrade</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navbar" %>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<div class="col-sm-6 col-sm-offset-3 col-xs-12">
  <%= yield :devise_content %>
</div>

<div class="container">
  <%= yield %>
<div class="container">
  
</body>
</html>

app/views/users/show.html.erb
<div class="page">
<h1>User Profile</h1>
  <br/>
  <p>E-mail: <a href="mailto:<%=@user.email%>"><%=@user.email%></a></p>
  <br/>
  <% if @user == current_user %>
    <%= link_to 'Add item', items_new_path, class: "btn btn-success btn-lg" %>
  <% end %>
  <br/>
  <br/>
  <div class="row">
    <h2>Available Items</h2>
  </div>
  <div class="row">
    <% @items = @user.items.order(:id).where "available = true" %>
    <% if @items.empty? %>
      <p>No available items.</p>
    <% else %>
      <%= render @items %>
    <% end %>
  </div>
  <% if @user == current_user %>
    <div class="row">
      <h2>Unavailable Items</h2>
    </div>
    <div class="row">
      <% @un_items = @user.items.order(:id).where "available = false" %>
      <% if @un_items.empty? %>
        <p>No unavailable items.</p>
      <% else %>
        <%= render @un_items%>
      <% end %>
    </div>
  <% end %>
</div>